question_data = [
    {"type": "multiple", "difficulty": "hard", "category": "Science: Computers",
     "question": "What vulnerability ranked #1 on the OWASP Top 10 in 2013?", "correct_answer": "Injection ",
     "incorrect_answers": ["Broken Authentication", "Cross-Site Scripting", "Insecure Direct Object References"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In &quot;Undertale&quot;, the main character of the game is Sans.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Who is the protagonist in the game &quot;The Walking Dead: Season One&quot;?",
     "correct_answer": "Lee Everett", "incorrect_answers": ["Clementine", "Kenny", "Rick Grimes"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Books",
     "question": "In Terry Pratchett&#039;s Discworld novel &#039;Wyrd Sisters&#039;, which of these are not one of the three main witches?",
     "correct_answer": "Winny Hathersham", "incorrect_answers": ["Granny Weatherwax", "Nanny Ogg", "Magrat Garlick"]},
    {"type": "multiple", "difficulty": "medium", "category": "Geography",
     "question": "Which of the following is not a megadiverse country - one that harbors a high number of the earth&#039;s endemic species?",
     "correct_answer": "Thailand", "incorrect_answers": ["Peru", "Mexico", "South Africa"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "When was the video game publisher &quot;Ubisoft&quot; founded ?", "correct_answer": "March 1986",
     "incorrect_answers": ["April 1990", "June 2001", "August 1956"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Television",
     "question": "What was the callsign of Commander William Adama in Battlestar Galactica (2004)?",
     "correct_answer": "Husker", "incorrect_answers": ["Starbuck", "Apollo", "Crashdown"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "Which of these artists did NOT remix the song &quot;Faded&quot; by Alan Walker?",
     "correct_answer": "Skrillex", "incorrect_answers": ["Ti&euml;sto", "Slushii", "Dash Berlin"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Minecraft can be played with a virtual reality headset.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                                       "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography", "question": "California is larger than Japan.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Video Games",
     "question": "In the National Pokedex what number is Porygon-Z?", "correct_answer": "474",
     "incorrect_answers": ["376", "432", "589"]}]
